version: "3.8"
services:

  postgres:
    image: "postgres:14-alpine"
    container_name: udemyinsta-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env

  api:
    image: ilvi/udemyinsta-api:latest
    container_name: udemyinsta-api
    build: ./api
    env_file:
      - ./env/api.env
    depends_on:
      - postgres

  frontend:
    image: ilvi/udemyinsta-frontend:latest
    container_name: udemyinsta-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    env_file:
      - ./env/frontend.env
    depends_on:
      - api

volumes:
  postgres-data: