version: "3.8"
services:

  postgres:
    image: "postgres"
    container_name: udemyinsta-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env

  api:
    image: ilvi/udemyinsta-api:latest
    container_name: udemyinsta-api
    build: ./api
    env_file:
      - ./env/api.env
    depends_on:
      - postgres

  frontend:
    image: ilvi/udemyinsta-frontend:latest
    container_name: udemyinsta-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    ports:
      - "3000:3000"
    # stdin_open: true
    # tty: true
    depends_on:
      - api

#  alembic:
#    build: ./api
#    env_file:
#      - ./env/backend.env
#    entrypoint: [ "alembic" ]
#    depends_on:
#      - postgres

volumes:
  postgres-data: