version: "3.8"
services:

  postgres:
    image: "postgres"
    container_name: udemyinsta-postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env

  backend:
    image: ilvi/udemyinsta-backend:latest
    container_name: udemyinsta-backend
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
#      - /app/temp_files
#      - backend-logs:/logs
    env_file:
      - ./env/backend.env
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  frontend:
    image: ilvi/udemyinsta-frontend:latest
    container_name: udemyinsta-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
#      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

#  alembic:
#    build: ./backend
#    volumes:
#      - ./backend:/app
#    env_file:
#      - ./env/backend.env
#    entrypoint: [ "alembic" ]
#    depends_on:
#      - postgres

volumes:
  postgres-data:
#  backend-logs: