version: "3.8"
services:

  postgres:
    image: "postgres:14-alpine"
    container_name: microinsta-postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env

  face:
    image: ilvi/microinsta-face:latest
    container_name: microinsta-face
    build: ./face
    expose:
      - 8081
    ports:
      - "8081:8081"
    volumes:
      - ./face/app:/appdir

  api:
    image: ilvi/microinsta-api:latest
    container_name: microinsta-api
    build: ./api
    expose:
      - 8000
    ports:
      - "8000:80"
    volumes:
      - ./api/app:/appdir/app
      - ./api/tests:/appdir/tests
#    command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 80"
    env_file:
      - ./env/api.env
    depends_on:
      - postgres
      - face

  frontend:
    image: ilvi/microinsta-frontend:latest
    container_name: microinsta-frontend
    build: ./frontend
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
#      - /app/node_modules
    stdin_open: true
    tty: true
    env_file:
      - ./env/frontend.env
    depends_on:
      - api

  alembic:
    image: ilvi/microinsta-alembic:latest
    container_name: microinsta-alembic
    build: ./api
    env_file:
      - ./env/api.env
    entrypoint: [ "alembic" ]
    depends_on:
      - postgres

volumes:
  postgres-data: