version: "3.8"
services:

  postgres:
    image: "postgres"
    container_name: udemyinsta-postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env

  api:
    image: ilvi/udemyinsta-api:latest
    container_name: udemyinsta-api
    build: ./api
    expose:
      - 8000
    ports:
      - "8000:80"
    volumes:
      - ./api/app:/app
      - ./api/tests:/tests
#    command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 80"
    env_file:
      - ./env/api.env
    depends_on:
      - postgres

  frontend:
    image: ilvi/udemyinsta-frontend:latest
    container_name: udemyinsta-frontend
    build: ./frontend
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
#      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api

  alembic:
    image: ilvi/udemyinsta-alembic:latest
    container_name: udemyinsta-alembic
    build: ./api
    env_file:
      - ./env/api.env
    entrypoint: [ "alembic" ]
    depends_on:
      - postgres

volumes:
  postgres-data: