"""add a field to post

Revision ID: e5523b9869ee
Revises: f858026af543
Create Date: 2022-11-09 08:19:50.984751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5523b9869ee'
down_revision = 'f858026af543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insta_post', sa.Column('prediction', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insta_post', 'prediction')
    # ### end Alembic commands ###
