apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ilvi/udemyinsta-api:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: insta-env
                  key: DATABASE_URL_VAL
