"""comments_cascade

Revision ID: 05b63d757e30
Revises: e5954a25adeb
Create Date: 2022-04-22 10:11:32.469074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b63d757e30'
down_revision = 'e5954a25adeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('insta_comment_post_id_fkey', 'insta_comment', type_='foreignkey')
    op.create_foreign_key(None, 'insta_comment', 'insta_post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insta_comment', type_='foreignkey')
    op.create_foreign_key('insta_comment_post_id_fkey', 'insta_comment', 'insta_post', ['post_id'], ['id'])
    # ### end Alembic commands ###
